image: node:latest

pages:
  script:
    - npm install  # Installiert die Abhängigkeiten
    - npm run build  # Führt den Build-Befehl aus
    - mv dist public  # Verschiebt das dist-Verzeichnis in das public-Verzeichnis
  artifacts:
    paths:
      - public
